# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt
# chmod 600 ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host public key:
# nix-shell -p ssh-to-age
# ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &users:
    - &haseeb_framework age1nfkkq86jk3yhhzgk3jt0kjzfpzv4qee3uheellawzgrmd296gczqa68yt7
    - &haseebmajid_dell age1s6rx9whkkf35t7qaju9vvla8tl2nstt0drx722ca4qadqfx66g0slxyxd0
    - &haseeb_framebox age1zm36rngg07hrm8nj3r8wj5ucz85njxzfwsxftsx3gtdmzkgw3peqh8vf55
    - &haseeb_vm age1x4x5ujnd9em23jhs53lgwqcmw9t6hx64xtdt3x0u4n66fsuygf9s4njjla
  - &hosts:
    - &framework age16lkhqtnle3z62gy0tk9x4tn3w43st2cnvdpl8r84xpzkn2f7jv8qxl5a9q
    - &vm age1pc0qdk5d2fen55cstvtch588wcqgzemgavlsvsc5dm0r4uw00vrq297et7
    - &framebox age199ny6lhask8zc65auwygqhj0svjkpp5kr7lhht8hvj947vaclecqrt4yg7
    - &vps age150twmyqdklep32scvp7vpr2djture8d5pu5jv7kpc6gdz4mg6svsxxlm9c

creation_rules:
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *framebox
      - *vm
      - *vps
      - *haseeb_framework
      - *haseeb_framebox
      - *haseeb_vm
      - *haseebmajid_dell

  - path_regex: modules/nixos/services/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *framebox
      - *vm
      - *vps
      - *haseeb_framework
      - *haseeb_framebox
      - *haseeb_vm
      - *haseebmajid_dell

  - path_regex: hosts/framebox/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *framebox
      - *vm
      - *haseeb_framework
      - *haseeb_framebox
      - *haseebmajid_dell

  - path_regex: hosts/framework/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *framebox
      - *haseeb_framework
      - *haseeb_framebox
      - *haseebmajid_dell

  - path_regex: modules/home/secrets.ya?ml$
    key_groups:
    - age:
      - *haseeb_framework
      - *haseeb_framebox
      - *haseeb_vm
      - *haseebmajid_dell
