keys:
  - &users:
    - &haseeb F04F743A24CD81B628A20667CD20E7373D83B71C
    - &haseebmajid F04F743A24CD81B628A20667CD20E7373D83B71C
  - &hosts:
    - &framework age1kzxen8ynw28h935jnjc9t8cx4p8mv6angk5suvkp6ntu4am9pe4smfw22z
    - &curve age1f44n6uklwmhfxthpq8k9ztq7q60k6g0u89ratdy3gurc0pqhhqjsx2x75g

creation_rules:
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      pgp:
      - *haseeb

  - path_regex: modules/home/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *curve
      pgp:
      - *haseeb
      - *haseebmajid

  - path_regex: modules/home/cli/programs/attic/secrets.yaml
    key_groups:
    - age:
      - *framework
      - *curve
      pgp:
      - *haseeb
      - *haseebmajid
