version: '3'

includes:
  install:
    taskfile: ./tasks/install.yml
    optional: true
  sops:
    taskfile: ./tasks/sops.yml
    optional: true

tasks:
  deploy:
    desc: "Deploy to host with deploy-rs"
    cmds:
      - |
        gum style --border rounded --padding "1 2" --border-foreground 212 "Deploy-rs Deployment"
        echo ""

        HOST=$(ls -1 hosts/ | gum choose --header "Select host to deploy")
        gum spin --spinner dot --title "Loading host configuration..." -- sleep 1

        DEPLOY_USER=$(gum input --placeholder "SSH user" --value "root")

        SKIP_CHECKS=$(gum choose --header "Skip deployment checks?" "No" "Yes")
        if [ "$SKIP_CHECKS" = "Yes" ]; then
          SKIP_CHECKS_FLAG="--skip-checks"
        else
          SKIP_CHECKS_FLAG=""
        fi

        REMOTE_BUILD=$(gum choose --header "Build on remote host?" "Yes" "No")
        if [ "$REMOTE_BUILD" = "Yes" ]; then
          REMOTE_BUILD_FLAG="--remote-build"
        else
          REMOTE_BUILD_FLAG=""
        fi

        gum confirm "Deploy to $HOST as $DEPLOY_USER?" || exit 0

        echo ""
        gum style --border double --padding "1 2" --border-foreground 212 "Starting deployment..."
        echo ""
        gum style "Host: $HOST" "User: $DEPLOY_USER"
        echo ""

        deploy .#$HOST --hostname $HOST --ssh-user $DEPLOY_USER $SKIP_CHECKS_FLAG $REMOTE_BUILD_FLAG

        DEPLOY_STATUS=$?

        echo ""
        if [ $DEPLOY_STATUS -eq 0 ]; then
          gum style --border rounded --padding "1 2" --border-foreground 2 "✓ Deployment complete!"
        else
          gum style --border rounded --padding "1 2" --border-foreground 196 "✗ Deployment failed!"
          exit 1
        fi

  rebuild:
    desc: "Rebuild on host"
    cmds:
      - |
        HOST=$(ls -1 hosts/ | gum choose)
        echo "Rebuilding $HOST..."
        rsync -av --exclude='.git' --exclude='result*' ./ haseeb@$HOST:~/nixicle/
        ssh haseeb@$HOST "cd ~/nixicle && sudo nixos-rebuild switch --flake .#$HOST"

  check:
    desc: "Check flake"
    cmds:
      - nix flake check

  fmt:
    desc: "Format Nix files"
    cmds:
      - nix fmt

  hosts:
    desc: "List available hosts"
    cmds:
      - echo "Available hosts:"
      - ls -1 hosts/
