abbr -U  g=git\
abbr -U  ga='git add'\
abbr -U  gaa='git add --all'\
abbr -U  gap='git apply'\
abbr -U  gapa='git add --patch'\
abbr -U  gb='git branch -vv'\
abbr -U  gbD='git branch -D'\
abbr -U  gba='git branch -a -v'\
abbr -U  gban='git branch -a -v --no-merged'\
abbr -U  gbd='git branch -d'\
abbr -U  gbl='git blame -b -w'\
abbr -U  gbs='git bisect'\
abbr -U  gbsb='git bisect bad'\
abbr -U  gbsg='git bisect good'\
abbr -U  gbsr='git bisect reset'\
abbr -U  gbss='git bisect start'\
abbr -U  gc='git commit -v'\
abbr -U  gc!='git commit -v --amend'\
abbr -U  gca='git commit -v -a'\
abbr -U  gca!='git commit -v -a --amend'\
abbr -U  gcam='git commit -a -m'\
abbr -U  gcan!='git commit -v -a --no-edit --amend'\
abbr -U  gcav='git commit -a -v --no-verify'\
abbr -U  gcav!='git commit -a -v --no-verify --amend'\
abbr -U  gcb='git checkout -b'\
abbr -U  gcf='git config --list'\
abbr -U  gcfx='git commit --fixup'\
abbr -U  gcl='git clone'\
abbr -U  gclean='git clean -di'\
abbr -U  gclean!='git clean -dfx'\
abbr -U  gcleanabbr import-fish abbrv='git reset --hard; and git clean -dfx'\
abbr -U  gcm='git commit -m'\
abbr -U  gcn!='git commit -v --no-edit --amend'\
abbr -U  gco='git checkout'\
abbr -U  gcod='git checkout develop'\
abbr -U  gcom='git checkout master'\
abbr -U  gcount='git shortlog -sn'\
abbr -U  gcp='git cherry-pick'\
abbr -U  gcpa='git cherry-pick --abort'\
abbr -U  gcpc='git cherry-pick --continue'\
abbr -U  gcv='git commit -v --no-verify'\
abbr -U  gd='git diff'\
abbr -U  gdca='git diff --cached'\
abbr -U  gds='git diff --stat'\
abbr -U  gdsc='git diff --stat --cached'\
abbr -U  gdw='git diff --word-diff'\
abbr -U  gdwc='git diff --word-diff --cached'\
abbr -U  gf='git fetch'\
abbr -U  gfa='git fetch --all --prune'\
abbr -U  gfb='git flow bugfix'\
abbr -U  gfbs='git flow bugfix start'\
abbr -U  gfbt='git flow bugfix track'\
abbr -U  gff='git flow feature'\
abbr -U  gffs='git flow feature start'\
abbr -U  gfft='git flow feature track'\
abbr -U  gfh='git flow hotfix'\
abbr -U  gfhs='git flow hotfix start'\
abbr -U  gfht='git flow hotfix track'\
abbr -U  gfm='git fetch origin master --prune; and git merge FETCH_HEAD'\
abbr -U  gfo='git fetch origin'\
abbr -U  gfp='git flow publish'\
abbr -U  gfr='git flow release'\
abbr -U  gfrs='git flow release start'\
abbr -U  gfrt='git flow release track'\
abbr -U  gfs='git flow support'\
abbr -U  gfss='git flow support start'\
abbr -U  gfst='git flow support track'\
abbr -U  ggp!='ggp --force-with-lease'\
abbr -U  gignore='git update-index --assume-unchanged'\
abbr -U  gl='git pull'\
abbr -U  glg='git log --stat --max-count=10'\
abbr -U  glgg='git log --graph --max-count=10'\
abbr -U  glgga='git log --graph --decorate --all'\
abbr -U  gll='git pull origin'\
abbr -U  glo='git log --oneline --decorate --color'\
abbr -U  glod='git log --oneline --decorate --color develop..'\
abbr -U  glog='git log --oneline --decorate --color --graph'\
abbr -U  glom='git log --oneline --decorate --color master..'\
abbr -U  gloo=git\ log\ --pretty=format:\'\%C\(yellow\)\%h\ \%Cred\%ad\ \%Cblue\%an\%Cgreen\%d\ \%Creset\%s\'\ --date=short\
abbr -U  glr='git pull --rebase'\
abbr -U  gm='git merge'\
abbr -U  gmt='git mergetool --no-prompt'\
abbr -U  gp='git push'\
abbr -U  gp!='git push --force-with-lease'\
abbr -U  gpo='git push origin'\
abbr -U  gpo!='git push --force-with-lease origin'\
abbr -U  gpu='ggp --set-upstream'\
abbr -U  gpv='git push --no-verify'\
abbr -U  gpv!='git push --no-verify --force-with-lease'\
abbr -U  gr='git remote -vv'\
abbr -U  gra='git remote add'\
abbr -U  grb='git rebase'\
abbr -U  grba='git rebase --abort'\
abbr -U  grbc='git rebase --continue'\
abbr -U  grbd='git rebase develop'\
abbr -U  grbdi='git rebase master --interactive'\
abbr -U  grbdia='git rebase master --interactive --autosquash'\
abbr -U  grbi='git rebase --interactive'\
abbr -U  grbm='git rebase master'\
abbr -U  grbmi='git rebase master --interactive'\
abbr -U  grbmia='git rebase master --interactive --autosquash'\
abbr -U  grbs='git rebase --skip'\
abbr -U  grev='git revert'\
abbr -U  grh='git reset'\
abbr -U  grhh='git reset --hard'\
abbr -U  grm='git rm'\
abbr -U  grmc='git rm --cached'\
abbr -U  grmv='git remote rename'\
abbr -U  grrm='git remote remove'\
abbr -U  grs='git restore'\
abbr -U  grset='git remote set-url'\
abbr -U  grss='git restore --source'\
abbr -U  grup='git remote update'\
abbr -U  grv='git remote -v'\
abbr -U  gscam='git commit -S -a -m'\
abbr -U  gsd='git svn dcommit'\
abbr -U  gsh='git show'\
abbr -U  gsr='git svn rebase'\
abbr -U  gss='git status -s'\
abbr -U  gst='git status'\
abbr -U  gsta='git stash'\
abbr -U  gstd='git stash drop'\
abbr -U  gstp='git stash pop'\
abbr -U  gsts='git stash show --text'\
abbr -U  gsu='git submodule update'\
abbr -U  gsur='git submodule update --recursive'\
abbr -U  gsuri='git submodule update --recursive --init'\
abbr -U  gsw='git switch'\
abbr -U  gswc='git switch --create'\
abbr -U  gts='git tag -s'\
abbr -U  gtv='git tag'\
abbr -U  gunignore='git update-index --no-assume-unchanged'\
abbr -U  gup='git pull --rebase'\
abbr -U  gwch='git whatchanged -p --abbrev-commit --pretty=medium'\