k3s_token: ENC[AES256_GCM,data:hua3VpAaC2Wh716OKxdfCUzTdJfXR5iLvk+u7wmzSw3Q46J2J6ZGSHVeBo7WL9l7+2xvkVhuYTqbiIqnKjxzzCyzY6CWYoFkwjuqxzpN+e/ThgZDEx1BAC8VFFBEQTream8k+ollszOOECqs,iv:bu7jfmvZhV8pWrdIOCuu+Gyj45f7E4KyZk+xgxs2imA=,tag:89o9TN0sZE23EpcQCQlKaA==,type:str]
sops:
    age:
        - recipient: age1vsjjdkgrv72tr3uftryj2szt3n0xk8h3ce54kzyfsmxtymxu6s4qgu5yuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsLy9WNG5WSkRoZmg3ZGFM
            YS9HQnNwSnRDbENHV2JGeGVwS3dCdkVRRUVjCnZzalM1NFpuNHMrTlR4eHNUNUdF
            SExTS3hqV1lmYVhqQVQ1dmJEdGcwQTQKLS0tIFFwZ3dpZmd6TSs3Z1R3Y3BDRVF5
            bmk2elRGYWJXNnpDNVNoajQzWWZURmsK/UcmUXYSxR0k0iahJCuuwgux7Z0x4F9+
            6b+GyB+OwLWWz4/N4F/jL8qGBAnWJ4vJqI6QXh/bKuQJ0htILKBIcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vmnnywhflwymjcgllmp5sgf05dn3qvamd2ylhxquwcuvlrm8ma3sc882mp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWmhNZE9ySjhMaU5obzQ5
            ZXZFVTd3eEVHVXFlTWhzYnI0OVBXQXM2TmdFCjNQOU04Yk5OYmdhZnJQUXIxL3Yr
            R1poUmZoL2JlcktGWmQ5Y2ZuSEhzK2MKLS0tIC9BeUVRL3JkWmdPdGcxUVg2VkIv
            UDhXdzFkUVRKTVErK2xQWERLRkZrdlEK1MwjDc1hZ+9+glIGwOw8a58cgqlFVUZx
            qE/1VFTJ6nXVi0nPICAjVg4B558sujB0Vj2dNFQctJM6H2IuS0VlXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6rhh8lvm9u0207gqf8wtk4eelatm7z6nvcyx5qxt4lkhk4lrq2swqcfpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RFJjSUdkZEFZTDk2U1Vk
            VVFlYXNTd05kaElGRS9nRnBBbzZQeCtHM1djCjF1eW81QUdJbE9ZV3NWMHFRN0sz
            VjU0MENidWErUk1TSUpXWnA5Q2NjUXcKLS0tIEM5M3JyTm9tQ0VxMFVOanZ6NlZ3
            YkFzUDQxNTJqTDJFU1gzK0FzSWhkY3MKhF1CaPGlviaUKxt5cD+8R9BdK1A0V5Io
            0npX0yM4tNYar0eAVVJ1hj59niZ6HNrxabF+MVY4ph81LdN1C7hVyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rc26esy506fa0kv2y97sjzfk4g2pr0ctv2rzkacewx5d8urns3zqhr7r7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeXRmYUNOekE3YVZVTWxU
            U0tsdFRIQVhCWTBuM2U4dmk1NE9ONHVVNEEwCnRlQW5FTGJONHJQOU95bklwUzVw
            YWx0cmsvYVNGaFNsdVgzdzlKS3hrbUUKLS0tIEJlRHNpM0g4enZRZURRMEE2cVlY
            L0lGbUpOUnVpTlJ3cXNFNW8rQkxoS0UKnknGIcJtGEdNUq4/AXxGxNU56GW7NBe2
            BkNzX7R8Guun88fgEK6+WGqFqfXRBa1GNGjBNTTTNjp0NkHIhJb7ZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vuljyz2m25vemv7djq8c5dwuwgl8m7g8lsr7tcnzrfh3mylkucrs39vueh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSk1IMU1BQjhQOUJyeUZL
            K2JORnFOLzU0aHFzQmVWS1Y0U3FhNFpUZW04Cno3RTcraUduV3duSGNzWE00N0tz
            TXI1UUF6MG1iWDBPUXhEaWlHV3ZyMVkKLS0tIGE4NTYwcFY0ZkdGMENiRnJqV1ps
            L3JBZnkyOTVBNzI4SFVyS2dEZFMxVlEKPRi8eMEfPNnEISNcnTDnhiTwMB67V/Xm
            +1buiGIHxYwdtXyN0veDZt6KpIOo9OnrAfgDh/RDVG9Xn0ZVRA+OYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rpqz5vl9tkgje46h43sjgthmqjcltwgm8fm9xdm9yk2ugemuqqrs6jpr43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOEpaRmlhWmJ4dGgrbGlW
            UW9TNytEb2w1MGFoWlJpWXc0bEtWclVhY1RVCk9DeEhFMm5XSklycmMxd0h3bEE1
            S3NiRldRZHI2SGs1NDdSV0JGbkNLN0UKLS0tIFRyNTIzOU8zZm90Zlk3d200MWlH
            NVN5YXVCMS9uaUVPOWl3RkRJL0djcm8KY0JYWlWnXmyrmMD2YwCe7WZkoOFwMFn2
            uQmqrvRVOyC6uRKxLmniTr4NHr7jxsy/RUFmB1KGJHAhLWXr59ojiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wtkcl8gwwumvzf78ttqy4gh2pwzz724glugs5wah2fcudgfh5pxq3urkpg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aEppbjY5VFNEQnFOcnAw
            dlhQVmRVVjlMK3g2N3NqU0R2ekVwZ3VtaDBNCk9WdUUxZUZmU0hvZkJsU0hUdGM3
            cDF3anVGcTZZc1JQOHZFLzZ1UE1UQjAKLS0tIFVNUklSZTNNQ3g4bEhjbXFzSFJN
            c3dYOS9iQ1VOLzhxdG41NUZjZWRiczQKSzKkMTL7doKTxbUFVj3DADUwPf1RE5zn
            1NpJbyzoE5n7bNgjdjCXCyzXK19NblX639cwmLA3JkiVoem6OZwU6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uswlqzs3pf99r6e8qq5d3eh44sufe5tdczmfqygeam7vfr96fugqa0pps7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXNkN3pibC8rd0VPUWRK
            NGZqY09LblZXYlhDekVJRTMrdEQ4bEZucm5VClI2MGdTS3lXdkpyVys3MWJTZmlI
            ZHlSaHZyNWV2Mi9lejZ5VkJhRitYY3MKLS0tIEZqbDBhN1JPOWFHSElCb0Z2cVR6
            eUN0YUFNaVRzSW1leDJtZm90UXBXNzQKWEmX56AifFLttT32DKGV/VO6inuM9HZs
            avDXzKsjmQvEGW0NPaj8G10V4/VCg+o4zoKmtsWDsZxF058AG3P6Bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19pl6jt7ekljfjww4g9anzafdxj0e52mnfnsyd26u5xdemfksqpwsnfwrs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUGwvL3p3RmNVZU1RYmNE
            Z0hkZUdxYmxLR1VzWWpSK2dCSXhJVWRPa0dJCngybEVldjErdnBPVW1BNVUzMDZt
            RGI0bmNUTllTdGI2YVBvSWZzMVk1MW8KLS0tIHd1QjZQTytFWmtaYjFKMkVFc2FG
            aFJiS0hMTFZjRDFEcmwxSFNaSExlcGcKlPqr8eKIl82bV23kf0l/u0UUy2pFjOE7
            nO5t/Uj9XoR4yL2w98biQ3lQyMlpfHsOoJnWD3+rfw1qRoJ7qVlo2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T11:32:52Z"
    mac: ENC[AES256_GCM,data:pHg4KMYMfTfoD+8C2R3sSkksy1iTopUyzBTIAIgLuf3mBX2xuUSW2bYErQbUBtfMDjob+WX05Gf9AlU63RuYgr2Gvct8fGRRZEjtfhIrGiFsHi/r9lwLMP633oiMFlUtL/iU/1LJnJzq4QcLBjkMVtKE3cWdD5VSFU9ouYtbOd4=,iv:04xnhcRLMUTAjulU6iWzuMGde45Fv2UDskUoVC1IaEw=,tag:QVCUf0t2QXwAviKdevWCnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
